// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: auth.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const claimInvite = `-- name: ClaimInvite :one
UPDATE worker_invite SET used_at = now()
WHERE id = $1 AND used_at IS NULL
RETURNING id
`

func (q *Queries) ClaimInvite(ctx context.Context, id uuid.UUID) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, claimInvite, id)
	var id_2 uuid.UUID
	err := row.Scan(&id_2)
	return id_2, err
}

const getActiveInvite = `-- name: GetActiveInvite :one
SELECT i.id, i.tenant_id, i.user_id, u.display_name
FROM worker_invite i
JOIN app_user u ON u.id = i.user_id
WHERE i.code = $1 AND i.used_at IS NULL AND i.expires_at > now()
`

type GetActiveInviteRow struct {
	ID          uuid.UUID
	TenantID    uuid.UUID
	UserID      uuid.UUID
	DisplayName string
}

func (q *Queries) GetActiveInvite(ctx context.Context, code string) (GetActiveInviteRow, error) {
	row := q.db.QueryRow(ctx, getActiveInvite, code)
	var i GetActiveInviteRow
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.UserID,
		&i.DisplayName,
	)
	return i, err
}

const getDeviceSession = `-- name: GetDeviceSession :one
SELECT u.id AS user_id, u.tenant_id, u.role
FROM device_token t
JOIN app_user u ON u.id = t.user_id
WHERE t.token_hash = $1
  AND t.revoked_at IS NULL
  AND u.is_active
`

type GetDeviceSessionRow struct {
	UserID   uuid.UUID
	TenantID uuid.UUID
	Role     UserRole
}

func (q *Queries) GetDeviceSession(ctx context.Context, tokenHash string) (GetDeviceSessionRow, error) {
	row := q.db.QueryRow(ctx, getDeviceSession, tokenHash)
	var i GetDeviceSessionRow
	err := row.Scan(&i.UserID, &i.TenantID, &i.Role)
	return i, err
}

const getRefreshToken = `-- name: GetRefreshToken :one
SELECT r.id, r.tenant_id, r.user_id, r.expires_at, r.used_at, r.revoked_at,
       u.role, u.is_active
FROM refresh_token r
JOIN app_user u ON u.id = r.user_id
WHERE r.token_hash = $1
`

type GetRefreshTokenRow struct {
	ID        uuid.UUID
	TenantID  uuid.UUID
	UserID    uuid.UUID
	ExpiresAt pgtype.Timestamptz
	UsedAt    pgtype.Timestamptz
	RevokedAt pgtype.Timestamptz
	Role      UserRole
	IsActive  bool
}

func (q *Queries) GetRefreshToken(ctx context.Context, tokenHash string) (GetRefreshTokenRow, error) {
	row := q.db.QueryRow(ctx, getRefreshToken, tokenHash)
	var i GetRefreshTokenRow
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.UserID,
		&i.ExpiresAt,
		&i.UsedAt,
		&i.RevokedAt,
		&i.Role,
		&i.IsActive,
	)
	return i, err
}

const getTenantStatus = `-- name: GetTenantStatus :one
SELECT status FROM tenant WHERE id = $1
`

func (q *Queries) GetTenantStatus(ctx context.Context, id uuid.UUID) (TenantStatus, error) {
	row := q.db.QueryRow(ctx, getTenantStatus, id)
	var status TenantStatus
	err := row.Scan(&status)
	return status, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, tenant_id, role, display_name, email, password_hash, is_active
FROM app_user
WHERE email = $1
`

type GetUserByEmailRow struct {
	ID           uuid.UUID
	TenantID     uuid.UUID
	Role         UserRole
	DisplayName  string
	Email        *string
	PasswordHash *string
	IsActive     bool
}

func (q *Queries) GetUserByEmail(ctx context.Context, email *string) (GetUserByEmailRow, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i GetUserByEmailRow
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Role,
		&i.DisplayName,
		&i.Email,
		&i.PasswordHash,
		&i.IsActive,
	)
	return i, err
}

const insertDeviceToken = `-- name: InsertDeviceToken :exec
INSERT INTO device_token (tenant_id, user_id, token_hash)
VALUES ($1, $2, $3)
`

type InsertDeviceTokenParams struct {
	TenantID  uuid.UUID
	UserID    uuid.UUID
	TokenHash string
}

func (q *Queries) InsertDeviceToken(ctx context.Context, arg InsertDeviceTokenParams) error {
	_, err := q.db.Exec(ctx, insertDeviceToken, arg.TenantID, arg.UserID, arg.TokenHash)
	return err
}

const insertRefreshToken = `-- name: InsertRefreshToken :exec
INSERT INTO refresh_token (tenant_id, user_id, token_hash, expires_at)
VALUES ($1, $2, $3, $4)
`

type InsertRefreshTokenParams struct {
	TenantID  uuid.UUID
	UserID    uuid.UUID
	TokenHash string
	ExpiresAt pgtype.Timestamptz
}

func (q *Queries) InsertRefreshToken(ctx context.Context, arg InsertRefreshTokenParams) error {
	_, err := q.db.Exec(ctx, insertRefreshToken,
		arg.TenantID,
		arg.UserID,
		arg.TokenHash,
		arg.ExpiresAt,
	)
	return err
}

const markRefreshTokenUsed = `-- name: MarkRefreshTokenUsed :exec
UPDATE refresh_token SET used_at = now() WHERE id = $1
`

func (q *Queries) MarkRefreshTokenUsed(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, markRefreshTokenUsed, id)
	return err
}

const revokeRefreshToken = `-- name: RevokeRefreshToken :exec
UPDATE refresh_token SET revoked_at = now()
WHERE token_hash = $1 AND revoked_at IS NULL
`

func (q *Queries) RevokeRefreshToken(ctx context.Context, tokenHash string) error {
	_, err := q.db.Exec(ctx, revokeRefreshToken, tokenHash)
	return err
}

const revokeUserRefreshTokens = `-- name: RevokeUserRefreshTokens :exec
UPDATE refresh_token SET revoked_at = now()
WHERE user_id = $1 AND revoked_at IS NULL
`

func (q *Queries) RevokeUserRefreshTokens(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.Exec(ctx, revokeUserRefreshTokens, userID)
	return err
}
