// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"database/sql/driver"
	"fmt"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type IssueSource string

const (
	IssueSourceWorker   IssueSource = "worker"
	IssueSourceManager  IssueSource = "manager"
	IssueSourcePublicQr IssueSource = "public_qr"
)

func (e *IssueSource) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = IssueSource(s)
	case string:
		*e = IssueSource(s)
	default:
		return fmt.Errorf("unsupported scan type for IssueSource: %T", src)
	}
	return nil
}

type NullIssueSource struct {
	IssueSource IssueSource
	Valid       bool // Valid is true if IssueSource is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullIssueSource) Scan(value interface{}) error {
	if value == nil {
		ns.IssueSource, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.IssueSource.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullIssueSource) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.IssueSource), nil
}

type IssueStatus string

const (
	IssueStatusOpen     IssueStatus = "open"
	IssueStatusAssigned IssueStatus = "assigned"
	IssueStatusResolved IssueStatus = "resolved"
	IssueStatusVerified IssueStatus = "verified"
	IssueStatusRejected IssueStatus = "rejected"
)

func (e *IssueStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = IssueStatus(s)
	case string:
		*e = IssueStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for IssueStatus: %T", src)
	}
	return nil
}

type NullIssueStatus struct {
	IssueStatus IssueStatus
	Valid       bool // Valid is true if IssueStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullIssueStatus) Scan(value interface{}) error {
	if value == nil {
		ns.IssueStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.IssueStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullIssueStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.IssueStatus), nil
}

type PhotoKind string

const (
	PhotoKindBefore     PhotoKind = "before"
	PhotoKindAfter      PhotoKind = "after"
	PhotoKindDefect     PhotoKind = "defect"
	PhotoKindResolution PhotoKind = "resolution"
)

func (e *PhotoKind) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = PhotoKind(s)
	case string:
		*e = PhotoKind(s)
	default:
		return fmt.Errorf("unsupported scan type for PhotoKind: %T", src)
	}
	return nil
}

type NullPhotoKind struct {
	PhotoKind PhotoKind
	Valid     bool // Valid is true if PhotoKind is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullPhotoKind) Scan(value interface{}) error {
	if value == nil {
		ns.PhotoKind, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.PhotoKind.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullPhotoKind) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.PhotoKind), nil
}

type ReportStatus string

const (
	ReportStatusGenerating ReportStatus = "generating"
	ReportStatusReady      ReportStatus = "ready"
	ReportStatusFailed     ReportStatus = "failed"
)

func (e *ReportStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ReportStatus(s)
	case string:
		*e = ReportStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for ReportStatus: %T", src)
	}
	return nil
}

type NullReportStatus struct {
	ReportStatus ReportStatus
	Valid        bool // Valid is true if ReportStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullReportStatus) Scan(value interface{}) error {
	if value == nil {
		ns.ReportStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ReportStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullReportStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ReportStatus), nil
}

type TenantStatus string

const (
	TenantStatusTrial     TenantStatus = "trial"
	TenantStatusActive    TenantStatus = "active"
	TenantStatusSuspended TenantStatus = "suspended"
	TenantStatusArchived  TenantStatus = "archived"
)

func (e *TenantStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = TenantStatus(s)
	case string:
		*e = TenantStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for TenantStatus: %T", src)
	}
	return nil
}

type NullTenantStatus struct {
	TenantStatus TenantStatus
	Valid        bool // Valid is true if TenantStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullTenantStatus) Scan(value interface{}) error {
	if value == nil {
		ns.TenantStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.TenantStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullTenantStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.TenantStatus), nil
}

type UserRole string

const (
	UserRoleAdmin   UserRole = "admin"
	UserRoleManager UserRole = "manager"
	UserRoleWorker  UserRole = "worker"
)

func (e *UserRole) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = UserRole(s)
	case string:
		*e = UserRole(s)
	default:
		return fmt.Errorf("unsupported scan type for UserRole: %T", src)
	}
	return nil
}

type NullUserRole struct {
	UserRole UserRole
	Valid    bool // Valid is true if UserRole is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullUserRole) Scan(value interface{}) error {
	if value == nil {
		ns.UserRole, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.UserRole.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullUserRole) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.UserRole), nil
}

type WorkOrderStatus string

const (
	WorkOrderStatusScheduled  WorkOrderStatus = "scheduled"
	WorkOrderStatusInProgress WorkOrderStatus = "in_progress"
	WorkOrderStatusDone       WorkOrderStatus = "done"
	WorkOrderStatusMissed     WorkOrderStatus = "missed"
)

func (e *WorkOrderStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = WorkOrderStatus(s)
	case string:
		*e = WorkOrderStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for WorkOrderStatus: %T", src)
	}
	return nil
}

type NullWorkOrderStatus struct {
	WorkOrderStatus WorkOrderStatus
	Valid           bool // Valid is true if WorkOrderStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullWorkOrderStatus) Scan(value interface{}) error {
	if value == nil {
		ns.WorkOrderStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.WorkOrderStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullWorkOrderStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.WorkOrderStatus), nil
}

type AppUser struct {
	ID           uuid.UUID
	TenantID     uuid.UUID
	Role         UserRole
	DisplayName  string
	Email        *string
	PasswordHash *string
	IsActive     bool
	CreatedAt    pgtype.Timestamptz
}

type ChecklistTemplate struct {
	ID        uuid.UUID
	TenantID  uuid.UUID
	Name      string
	CreatedAt pgtype.Timestamptz
}

type ChecklistTemplateItem struct {
	ID            uuid.UUID
	VersionID     uuid.UUID
	Position      int32
	Title         string
	RequiresPhoto bool
}

type ChecklistTemplateVersion struct {
	ID          uuid.UUID
	TemplateID  uuid.UUID
	Version     int32
	PublishedAt pgtype.Timestamptz
}

type Contract struct {
	ID         uuid.UUID
	TenantID   uuid.UUID
	Name       string
	ClientName *string
	CreatedAt  pgtype.Timestamptz
}

type DeviceToken struct {
	ID        uuid.UUID
	TenantID  uuid.UUID
	UserID    uuid.UUID
	TokenHash string
	CreatedAt pgtype.Timestamptz
	RevokedAt pgtype.Timestamptz
}

type Issue struct {
	ID          uuid.UUID
	TenantID    uuid.UUID
	ObjectID    uuid.UUID
	Source      IssueSource
	ReporterID  uuid.NullUUID
	Title       string
	Description *string
	Status      IssueStatus
	AssigneeID  uuid.NullUUID
	DueDate     pgtype.Date
	CreatedAt   pgtype.Timestamptz
}

type IssueResolution struct {
	ID          uuid.UUID
	TenantID    uuid.UUID
	IssueID     uuid.UUID
	ResolverID  uuid.UUID
	ExecutionID uuid.NullUUID
	ResolvedAt  pgtype.Timestamptz
	Note        *string
}

type Object struct {
	ID         uuid.UUID
	TenantID   uuid.UUID
	Name       string
	Address    *string
	Lat        *float64
	Lon        *float64
	Kind       *string
	QrToken    *string
	ContractID uuid.NullUUID
	IsActive   bool
	CreatedAt  pgtype.Timestamptz
}

type OpsAudit struct {
	ID          uuid.UUID
	Action      string
	TenantID    uuid.NullUUID
	Detail      []byte
	PerformedAt pgtype.Timestamptz
}

type Photo struct {
	ID           uuid.UUID
	TenantID     uuid.UUID
	ExecutionID  uuid.NullUUID
	IssueID      uuid.NullUUID
	ResolutionID uuid.NullUUID
	Kind         PhotoKind
	S3Key        string
	TakenAt      pgtype.Timestamptz
	Lat          *float64
	Lon          *float64
	UploadedAt   pgtype.Timestamptz
	CreatedAt    pgtype.Timestamptz
}

type RefreshToken struct {
	ID        uuid.UUID
	TenantID  uuid.UUID
	UserID    uuid.UUID
	TokenHash string
	CreatedAt pgtype.Timestamptz
	ExpiresAt pgtype.Timestamptz
	UsedAt    pgtype.Timestamptz
	RevokedAt pgtype.Timestamptz
}

type Report struct {
	ID             uuid.UUID
	TenantID       uuid.UUID
	ContractID     uuid.NullUUID
	PeriodFrom     pgtype.Date
	PeriodTo       pgtype.Date
	Status         ReportStatus
	FailureReason  *string
	S3Key          *string
	GeneratedAt    pgtype.Timestamptz
	GeneratedBy    uuid.NullUUID
	CreatedAt      pgtype.Timestamptz
	RenderAttempts int32
}

type Tenant struct {
	ID          uuid.UUID
	Name        string
	Status      TenantStatus
	TrialEndsAt pgtype.Timestamptz
	PlanNote    *string
	BilledUntil pgtype.Date
	OpsNote     *string
	CreatedAt   pgtype.Timestamptz
	Timezone    string
	SuspendedAt pgtype.Timestamptz
}

type WorkExecution struct {
	ID               uuid.UUID
	TenantID         uuid.UUID
	WorkOrderID      uuid.UUID
	WorkerID         uuid.UUID
	StartedAt        pgtype.Timestamptz
	FinishedAt       pgtype.Timestamptz
	DeviceFinishedAt pgtype.Timestamptz
	Note             *string
	CreatedAt        pgtype.Timestamptz
}

type WorkExecutionItem struct {
	ID             uuid.UUID
	ExecutionID    uuid.UUID
	TemplateItemID uuid.UUID
	Checked        bool
	CheckedAt      pgtype.Timestamptz
}

type WorkOrder struct {
	ID         uuid.UUID
	TenantID   uuid.UUID
	ObjectID   uuid.UUID
	VersionID  uuid.UUID
	AssigneeID uuid.NullUUID
	DueDate    pgtype.Date
	Status     WorkOrderStatus
	CreatedAt  pgtype.Timestamptz
}

type WorkerInvite struct {
	ID        uuid.UUID
	TenantID  uuid.UUID
	UserID    uuid.UUID
	Code      string
	ExpiresAt pgtype.Timestamptz
	UsedAt    pgtype.Timestamptz
}
