// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: object.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const listObjects = `-- name: ListObjects :many
SELECT id, name, address, lat, lon, kind, qr_token, contract_id, is_active, created_at
FROM object
WHERE tenant_id = $1
  AND ($2::boolean IS NULL OR is_active = $2)
  AND ($3::uuid IS NULL OR contract_id = $3)
ORDER BY name
`

type ListObjectsParams struct {
	TenantID   uuid.UUID
	Active     *bool
	ContractID uuid.NullUUID
}

type ListObjectsRow struct {
	ID         uuid.UUID
	Name       string
	Address    *string
	Lat        *float64
	Lon        *float64
	Kind       *string
	QrToken    *string
	ContractID uuid.NullUUID
	IsActive   bool
	CreatedAt  pgtype.Timestamptz
}

func (q *Queries) ListObjects(ctx context.Context, arg ListObjectsParams) ([]ListObjectsRow, error) {
	rows, err := q.db.Query(ctx, listObjects, arg.TenantID, arg.Active, arg.ContractID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListObjectsRow
	for rows.Next() {
		var i ListObjectsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Address,
			&i.Lat,
			&i.Lon,
			&i.Kind,
			&i.QrToken,
			&i.ContractID,
			&i.IsActive,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
