// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: platform.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const deletePhotoRow = `-- name: DeletePhotoRow :exec
DELETE FROM photo WHERE id = $1 AND uploaded_at IS NULL
`

func (q *Queries) DeletePhotoRow(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deletePhotoRow, id)
	return err
}

const getTenantByName = `-- name: GetTenantByName :one
SELECT id FROM tenant WHERE name = $1
`

// The demo seeder's idempotence guard (cmd/seed): tenant.name has no unique
// constraint (multiple real customers could share a display name), so this
// is a plain lookup, not a uniqueness check — the seeder only ever queries
// its own fixed demo tenant name.
func (q *Queries) GetTenantByName(ctx context.Context, name string) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, getTenantByName, name)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const getTenantSuspension = `-- name: GetTenantSuspension :one
SELECT suspended_at FROM tenant WHERE id = $1
`

func (q *Queries) GetTenantSuspension(ctx context.Context, id uuid.UUID) (pgtype.Timestamptz, error) {
	row := q.db.QueryRow(ctx, getTenantSuspension, id)
	var suspended_at pgtype.Timestamptz
	err := row.Scan(&suspended_at)
	return suspended_at, err
}

const insertOpsAudit = `-- name: InsertOpsAudit :exec
INSERT INTO ops_audit (action, tenant_id, detail) VALUES ($1, $2, $3)
`

type InsertOpsAuditParams struct {
	Action   string
	TenantID uuid.NullUUID
	Detail   []byte
}

func (q *Queries) InsertOpsAudit(ctx context.Context, arg InsertOpsAuditParams) error {
	_, err := q.db.Exec(ctx, insertOpsAudit, arg.Action, arg.TenantID, arg.Detail)
	return err
}

const listOrphanPhotos = `-- name: ListOrphanPhotos :many
SELECT id, s3_key FROM photo
WHERE uploaded_at IS NULL AND created_at < $1
ORDER BY created_at LIMIT 100
`

type ListOrphanPhotosRow struct {
	ID    uuid.UUID
	S3Key string
}

func (q *Queries) ListOrphanPhotos(ctx context.Context, createdAt pgtype.Timestamptz) ([]ListOrphanPhotosRow, error) {
	rows, err := q.db.Query(ctx, listOrphanPhotos, createdAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListOrphanPhotosRow
	for rows.Next() {
		var i ListOrphanPhotosRow
		if err := rows.Scan(&i.ID, &i.S3Key); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTenantTimezones = `-- name: ListTenantTimezones :many
SELECT id, timezone FROM tenant
`

type ListTenantTimezonesRow struct {
	ID       uuid.UUID
	Timezone string
}

// Scheduler-internal: the per-tenant fan-out for missed-order marking. Every
// status is included -- a suspended tenant's order history must stay honest
// too (docs/12: suspension is read-only, not history-freezing).
func (q *Queries) ListTenantTimezones(ctx context.Context) ([]ListTenantTimezonesRow, error) {
	rows, err := q.db.Query(ctx, listTenantTimezones)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListTenantTimezonesRow
	for rows.Next() {
		var i ListTenantTimezonesRow
		if err := rows.Scan(&i.ID, &i.Timezone); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markTenantOverdueOrdersMissed = `-- name: MarkTenantOverdueOrdersMissed :execrows
UPDATE work_order SET status = 'missed'
WHERE tenant_id = $1
  AND status = 'scheduled'
  AND due_date < $2
`

type MarkTenantOverdueOrdersMissedParams struct {
	TenantID    uuid.UUID
	TenantToday pgtype.Date
}

// One tenant's slice of the hourly missed-marking sweep: an order is missed
// once the tenant's local date has moved past due_date. tenant_today is
// computed in Go (Scheduler.markOverdueMissed) so one tenant's invalid
// timezone can never fail the sweep for every other tenant.
func (q *Queries) MarkTenantOverdueOrdersMissed(ctx context.Context, arg MarkTenantOverdueOrdersMissedParams) (int64, error) {
	result, err := q.db.Exec(ctx, markTenantOverdueOrdersMissed, arg.TenantID, arg.TenantToday)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const opsCreateTenant = `-- name: OpsCreateTenant :one
INSERT INTO tenant (name, trial_ends_at) VALUES ($1, $2)
RETURNING id, name, status, trial_ends_at
`

type OpsCreateTenantParams struct {
	Name        string
	TrialEndsAt pgtype.Timestamptz
}

type OpsCreateTenantRow struct {
	ID          uuid.UUID
	Name        string
	Status      TenantStatus
	TrialEndsAt pgtype.Timestamptz
}

func (q *Queries) OpsCreateTenant(ctx context.Context, arg OpsCreateTenantParams) (OpsCreateTenantRow, error) {
	row := q.db.QueryRow(ctx, opsCreateTenant, arg.Name, arg.TrialEndsAt)
	var i OpsCreateTenantRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Status,
		&i.TrialEndsAt,
	)
	return i, err
}

const opsInsertAdminUser = `-- name: OpsInsertAdminUser :one
INSERT INTO app_user (tenant_id, role, display_name, email, password_hash)
VALUES ($1, 'admin', $2, $3, $4)
RETURNING id
`

type OpsInsertAdminUserParams struct {
	TenantID     uuid.UUID
	DisplayName  string
	Email        *string
	PasswordHash *string
}

// The operator CLI's only user-creation path: OpsCreateTenant's first admin.
// Role is hardcoded 'admin' -- ops never creates any other role.
func (q *Queries) OpsInsertAdminUser(ctx context.Context, arg OpsInsertAdminUserParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, opsInsertAdminUser,
		arg.TenantID,
		arg.DisplayName,
		arg.Email,
		arg.PasswordHash,
	)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const opsListTenants = `-- name: OpsListTenants :many
SELECT t.id, t.name, t.status, t.timezone, t.trial_ends_at, t.billed_until, t.suspended_at,
       (SELECT count(*) FROM app_user u WHERE u.tenant_id = t.id AND u.role = 'worker' AND u.is_active) AS active_workers,
       (SELECT count(*) FROM object o WHERE o.tenant_id = t.id AND o.is_active) AS active_objects
FROM tenant t ORDER BY t.name
`

type OpsListTenantsRow struct {
	ID            uuid.UUID
	Name          string
	Status        TenantStatus
	Timezone      string
	TrialEndsAt   pgtype.Timestamptz
	BilledUntil   pgtype.Date
	SuspendedAt   pgtype.Timestamptz
	ActiveWorkers int64
	ActiveObjects int64
}

func (q *Queries) OpsListTenants(ctx context.Context) ([]OpsListTenantsRow, error) {
	rows, err := q.db.Query(ctx, opsListTenants)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []OpsListTenantsRow
	for rows.Next() {
		var i OpsListTenantsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Status,
			&i.Timezone,
			&i.TrialEndsAt,
			&i.BilledUntil,
			&i.SuspendedAt,
			&i.ActiveWorkers,
			&i.ActiveObjects,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const opsSetBilling = `-- name: OpsSetBilling :exec
UPDATE tenant SET billed_until = $2, plan_note = COALESCE($3, plan_note)
WHERE id = $1
`

type OpsSetBillingParams struct {
	ID          uuid.UUID
	BilledUntil pgtype.Date
	PlanNote    *string
}

func (q *Queries) OpsSetBilling(ctx context.Context, arg OpsSetBillingParams) error {
	_, err := q.db.Exec(ctx, opsSetBilling, arg.ID, arg.BilledUntil, arg.PlanNote)
	return err
}

const opsSetTenantStatus = `-- name: OpsSetTenantStatus :exec
UPDATE tenant SET status = $2, suspended_at = $3 WHERE id = $1
`

type OpsSetTenantStatusParams struct {
	ID          uuid.UUID
	Status      TenantStatus
	SuspendedAt pgtype.Timestamptz
}

func (q *Queries) OpsSetTenantStatus(ctx context.Context, arg OpsSetTenantStatusParams) error {
	_, err := q.db.Exec(ctx, opsSetTenantStatus, arg.ID, arg.Status, arg.SuspendedAt)
	return err
}

const setTenantTimezone = `-- name: SetTenantTimezone :execrows
UPDATE tenant SET timezone = $2
WHERE id = $1 AND EXISTS (SELECT 1 FROM pg_catalog.pg_timezone_names WHERE name = $2)
`

type SetTenantTimezoneParams struct {
	ID       uuid.UUID
	Timezone string
}

// Guarded by pg_timezone_names: an unknown zone updates zero rows (the
// caller treats 0 as an error), so an invalid string can never enter
// tenant.timezone through this path and later trip the scheduler's or the
// report renderer's zone lookup.
func (q *Queries) SetTenantTimezone(ctx context.Context, arg SetTenantTimezoneParams) (int64, error) {
	result, err := q.db.Exec(ctx, setTenantTimezone, arg.ID, arg.Timezone)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
