// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: platform.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const deletePhotoRow = `-- name: DeletePhotoRow :exec
DELETE FROM photo WHERE id = $1 AND uploaded_at IS NULL
`

func (q *Queries) DeletePhotoRow(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deletePhotoRow, id)
	return err
}

const getTenantSuspension = `-- name: GetTenantSuspension :one
SELECT suspended_at FROM tenant WHERE id = $1
`

func (q *Queries) GetTenantSuspension(ctx context.Context, id uuid.UUID) (pgtype.Timestamptz, error) {
	row := q.db.QueryRow(ctx, getTenantSuspension, id)
	var suspended_at pgtype.Timestamptz
	err := row.Scan(&suspended_at)
	return suspended_at, err
}

const insertOpsAudit = `-- name: InsertOpsAudit :exec
INSERT INTO ops_audit (action, tenant_id, detail) VALUES ($1, $2, $3)
`

type InsertOpsAuditParams struct {
	Action   string
	TenantID uuid.NullUUID
	Detail   []byte
}

func (q *Queries) InsertOpsAudit(ctx context.Context, arg InsertOpsAuditParams) error {
	_, err := q.db.Exec(ctx, insertOpsAudit, arg.Action, arg.TenantID, arg.Detail)
	return err
}

const listOrphanPhotos = `-- name: ListOrphanPhotos :many
SELECT id, s3_key FROM photo
WHERE uploaded_at IS NULL AND created_at < $1
ORDER BY created_at LIMIT 100
`

type ListOrphanPhotosRow struct {
	ID    uuid.UUID
	S3Key string
}

func (q *Queries) ListOrphanPhotos(ctx context.Context, createdAt pgtype.Timestamptz) ([]ListOrphanPhotosRow, error) {
	rows, err := q.db.Query(ctx, listOrphanPhotos, createdAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListOrphanPhotosRow
	for rows.Next() {
		var i ListOrphanPhotosRow
		if err := rows.Scan(&i.ID, &i.S3Key); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markOverdueOrdersMissed = `-- name: MarkOverdueOrdersMissed :execrows
UPDATE work_order wo SET status = 'missed'
FROM tenant t
WHERE t.id = wo.tenant_id
  AND wo.status = 'scheduled'
  AND wo.due_date < (now() AT TIME ZONE t.timezone)::date
`

// Tenant-timezone-aware: an order is missed once ITS tenant's local date has
// moved past due_date. Cross-tenant by design (the scheduler serves all tenants).
func (q *Queries) MarkOverdueOrdersMissed(ctx context.Context) (int64, error) {
	result, err := q.db.Exec(ctx, markOverdueOrdersMissed)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const opsCreateTenant = `-- name: OpsCreateTenant :one
INSERT INTO tenant (name, trial_ends_at) VALUES ($1, $2)
RETURNING id, name, status, trial_ends_at
`

type OpsCreateTenantParams struct {
	Name        string
	TrialEndsAt pgtype.Timestamptz
}

type OpsCreateTenantRow struct {
	ID          uuid.UUID
	Name        string
	Status      TenantStatus
	TrialEndsAt pgtype.Timestamptz
}

func (q *Queries) OpsCreateTenant(ctx context.Context, arg OpsCreateTenantParams) (OpsCreateTenantRow, error) {
	row := q.db.QueryRow(ctx, opsCreateTenant, arg.Name, arg.TrialEndsAt)
	var i OpsCreateTenantRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Status,
		&i.TrialEndsAt,
	)
	return i, err
}

const opsInsertAdminUser = `-- name: OpsInsertAdminUser :one
INSERT INTO app_user (tenant_id, role, display_name, email, password_hash)
VALUES ($1, 'admin', $2, $3, $4)
RETURNING id
`

type OpsInsertAdminUserParams struct {
	TenantID     uuid.UUID
	DisplayName  string
	Email        *string
	PasswordHash *string
}

// The operator CLI's only user-creation path: OpsCreateTenant's first admin.
// Role is hardcoded 'admin' -- ops never creates any other role.
func (q *Queries) OpsInsertAdminUser(ctx context.Context, arg OpsInsertAdminUserParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, opsInsertAdminUser,
		arg.TenantID,
		arg.DisplayName,
		arg.Email,
		arg.PasswordHash,
	)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const opsListTenants = `-- name: OpsListTenants :many
SELECT t.id, t.name, t.status, t.timezone, t.trial_ends_at, t.billed_until, t.suspended_at,
       (SELECT count(*) FROM app_user u WHERE u.tenant_id = t.id AND u.role = 'worker' AND u.is_active) AS active_workers,
       (SELECT count(*) FROM object o WHERE o.tenant_id = t.id AND o.is_active) AS active_objects
FROM tenant t ORDER BY t.name
`

type OpsListTenantsRow struct {
	ID            uuid.UUID
	Name          string
	Status        TenantStatus
	Timezone      string
	TrialEndsAt   pgtype.Timestamptz
	BilledUntil   pgtype.Date
	SuspendedAt   pgtype.Timestamptz
	ActiveWorkers int64
	ActiveObjects int64
}

func (q *Queries) OpsListTenants(ctx context.Context) ([]OpsListTenantsRow, error) {
	rows, err := q.db.Query(ctx, opsListTenants)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []OpsListTenantsRow
	for rows.Next() {
		var i OpsListTenantsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Status,
			&i.Timezone,
			&i.TrialEndsAt,
			&i.BilledUntil,
			&i.SuspendedAt,
			&i.ActiveWorkers,
			&i.ActiveObjects,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const opsSetBilling = `-- name: OpsSetBilling :exec
UPDATE tenant SET billed_until = $2, plan_note = COALESCE($3, plan_note)
WHERE id = $1
`

type OpsSetBillingParams struct {
	ID          uuid.UUID
	BilledUntil pgtype.Date
	PlanNote    *string
}

func (q *Queries) OpsSetBilling(ctx context.Context, arg OpsSetBillingParams) error {
	_, err := q.db.Exec(ctx, opsSetBilling, arg.ID, arg.BilledUntil, arg.PlanNote)
	return err
}

const opsSetTenantStatus = `-- name: OpsSetTenantStatus :exec
UPDATE tenant SET status = $2, suspended_at = $3 WHERE id = $1
`

type OpsSetTenantStatusParams struct {
	ID          uuid.UUID
	Status      TenantStatus
	SuspendedAt pgtype.Timestamptz
}

func (q *Queries) OpsSetTenantStatus(ctx context.Context, arg OpsSetTenantStatusParams) error {
	_, err := q.db.Exec(ctx, opsSetTenantStatus, arg.ID, arg.Status, arg.SuspendedAt)
	return err
}
