// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: report.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const claimNextReport = `-- name: ClaimNextReport :one
UPDATE report SET render_attempts = render_attempts + 1
WHERE id = (
    SELECT id FROM report
    WHERE status = 'generating' AND render_attempts < 3
    ORDER BY created_at
    LIMIT 1
    FOR UPDATE SKIP LOCKED
)
RETURNING id, tenant_id, contract_id, period_from, period_to, render_attempts
`

type ClaimNextReportRow struct {
	ID             uuid.UUID
	TenantID       uuid.UUID
	ContractID     uuid.NullUUID
	PeriodFrom     pgtype.Date
	PeriodTo       pgtype.Date
	RenderAttempts int32
}

// Worker-internal: drains the queue across ALL tenants (single in-process
// worker). SKIP LOCKED lets a future second instance coexist safely.
func (q *Queries) ClaimNextReport(ctx context.Context) (ClaimNextReportRow, error) {
	row := q.db.QueryRow(ctx, claimNextReport)
	var i ClaimNextReportRow
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.ContractID,
		&i.PeriodFrom,
		&i.PeriodTo,
		&i.RenderAttempts,
	)
	return i, err
}

const getContractName = `-- name: GetContractName :one
SELECT name, client_name FROM contract WHERE id = $1 AND tenant_id = $2
`

type GetContractNameParams struct {
	ID       uuid.UUID
	TenantID uuid.UUID
}

type GetContractNameRow struct {
	Name       string
	ClientName *string
}

func (q *Queries) GetContractName(ctx context.Context, arg GetContractNameParams) (GetContractNameRow, error) {
	row := q.db.QueryRow(ctx, getContractName, arg.ID, arg.TenantID)
	var i GetContractNameRow
	err := row.Scan(&i.Name, &i.ClientName)
	return i, err
}

const getReport = `-- name: GetReport :one
SELECT id, contract_id, period_from, period_to, status, failure_reason, s3_key, generated_at, created_at
FROM report WHERE id = $1 AND tenant_id = $2
`

type GetReportParams struct {
	ID       uuid.UUID
	TenantID uuid.UUID
}

type GetReportRow struct {
	ID            uuid.UUID
	ContractID    uuid.NullUUID
	PeriodFrom    pgtype.Date
	PeriodTo      pgtype.Date
	Status        ReportStatus
	FailureReason *string
	S3Key         *string
	GeneratedAt   pgtype.Timestamptz
	CreatedAt     pgtype.Timestamptz
}

func (q *Queries) GetReport(ctx context.Context, arg GetReportParams) (GetReportRow, error) {
	row := q.db.QueryRow(ctx, getReport, arg.ID, arg.TenantID)
	var i GetReportRow
	err := row.Scan(
		&i.ID,
		&i.ContractID,
		&i.PeriodFrom,
		&i.PeriodTo,
		&i.Status,
		&i.FailureReason,
		&i.S3Key,
		&i.GeneratedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getTenantForReport = `-- name: GetTenantForReport :one
SELECT name, timezone FROM tenant WHERE id = $1
`

type GetTenantForReportRow struct {
	Name     string
	Timezone string
}

// timezone: report times (job completion, photo captions) print in the
// tenant's local wall clock — the zone the inspector and the worker live in.
func (q *Queries) GetTenantForReport(ctx context.Context, id uuid.UUID) (GetTenantForReportRow, error) {
	row := q.db.QueryRow(ctx, getTenantForReport, id)
	var i GetTenantForReportRow
	err := row.Scan(&i.Name, &i.Timezone)
	return i, err
}

const insertReport = `-- name: InsertReport :one
INSERT INTO report (tenant_id, contract_id, period_from, period_to, generated_by)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, status, created_at
`

type InsertReportParams struct {
	TenantID    uuid.UUID
	ContractID  uuid.NullUUID
	PeriodFrom  pgtype.Date
	PeriodTo    pgtype.Date
	GeneratedBy uuid.NullUUID
}

type InsertReportRow struct {
	ID        uuid.UUID
	Status    ReportStatus
	CreatedAt pgtype.Timestamptz
}

func (q *Queries) InsertReport(ctx context.Context, arg InsertReportParams) (InsertReportRow, error) {
	row := q.db.QueryRow(ctx, insertReport,
		arg.TenantID,
		arg.ContractID,
		arg.PeriodFrom,
		arg.PeriodTo,
		arg.GeneratedBy,
	)
	var i InsertReportRow
	err := row.Scan(&i.ID, &i.Status, &i.CreatedAt)
	return i, err
}

const listReports = `-- name: ListReports :many
SELECT id, contract_id, period_from, period_to, status, generated_at, created_at
FROM report WHERE tenant_id = $1
ORDER BY created_at DESC LIMIT 100
`

type ListReportsRow struct {
	ID          uuid.UUID
	ContractID  uuid.NullUUID
	PeriodFrom  pgtype.Date
	PeriodTo    pgtype.Date
	Status      ReportStatus
	GeneratedAt pgtype.Timestamptz
	CreatedAt   pgtype.Timestamptz
}

func (q *Queries) ListReports(ctx context.Context, tenantID uuid.UUID) ([]ListReportsRow, error) {
	rows, err := q.db.Query(ctx, listReports, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListReportsRow
	for rows.Next() {
		var i ListReportsRow
		if err := rows.Scan(
			&i.ID,
			&i.ContractID,
			&i.PeriodFrom,
			&i.PeriodTo,
			&i.Status,
			&i.GeneratedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markReportFailed = `-- name: MarkReportFailed :exec
UPDATE report SET status = 'failed', failure_reason = $2
WHERE id = $1 AND status = 'generating'
`

type MarkReportFailedParams struct {
	ID            uuid.UUID
	FailureReason *string
}

func (q *Queries) MarkReportFailed(ctx context.Context, arg MarkReportFailedParams) error {
	_, err := q.db.Exec(ctx, markReportFailed, arg.ID, arg.FailureReason)
	return err
}

const markReportReady = `-- name: MarkReportReady :exec
UPDATE report SET status = 'ready', s3_key = $2, generated_at = now()
WHERE id = $1 AND status = 'generating'
`

type MarkReportReadyParams struct {
	ID    uuid.UUID
	S3Key *string
}

func (q *Queries) MarkReportReady(ctx context.Context, arg MarkReportReadyParams) error {
	_, err := q.db.Exec(ctx, markReportReady, arg.ID, arg.S3Key)
	return err
}

const reportExecutionPhotos = `-- name: ReportExecutionPhotos :many
SELECT execution_id, id, kind, s3_key, taken_at, lat, lon, uploaded_at
FROM photo
WHERE tenant_id = $1
  AND execution_id = ANY($2::uuid[])
ORDER BY execution_id, kind, id
`

type ReportExecutionPhotosParams struct {
	TenantID     uuid.UUID
	ExecutionIds []uuid.UUID
}

type ReportExecutionPhotosRow struct {
	ExecutionID uuid.NullUUID
	ID          uuid.UUID
	Kind        PhotoKind
	S3Key       string
	TakenAt     pgtype.Timestamptz
	Lat         *float64
	Lon         *float64
	UploadedAt  pgtype.Timestamptz
}

// kind ASC sorts by photo_kind's DECLARATION order (Postgres enum semantics,
// not alphabetical): before, after, defect, resolution — before precedes
// after in the report's photo grid (docs/09).
func (q *Queries) ReportExecutionPhotos(ctx context.Context, arg ReportExecutionPhotosParams) ([]ReportExecutionPhotosRow, error) {
	rows, err := q.db.Query(ctx, reportExecutionPhotos, arg.TenantID, arg.ExecutionIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ReportExecutionPhotosRow
	for rows.Next() {
		var i ReportExecutionPhotosRow
		if err := rows.Scan(
			&i.ExecutionID,
			&i.ID,
			&i.Kind,
			&i.S3Key,
			&i.TakenAt,
			&i.Lat,
			&i.Lon,
			&i.UploadedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const reportMissedOrders = `-- name: ReportMissedOrders :many
SELECT wo.object_id, o.name AS object_name, wo.due_date
FROM work_order wo
JOIN object o ON o.id = wo.object_id AND o.tenant_id = wo.tenant_id
WHERE wo.tenant_id = $1
  AND wo.status = 'missed'
  AND wo.due_date BETWEEN $2 AND $3
  AND ($4::uuid IS NULL OR o.contract_id = $4)
ORDER BY o.address NULLS LAST, o.name, wo.due_date
`

type ReportMissedOrdersParams struct {
	TenantID   uuid.UUID
	PeriodFrom pgtype.Date
	PeriodTo   pgtype.Date
	ContractID uuid.NullUUID
}

type ReportMissedOrdersRow struct {
	ObjectID   uuid.UUID
	ObjectName string
	DueDate    pgtype.Date
}

func (q *Queries) ReportMissedOrders(ctx context.Context, arg ReportMissedOrdersParams) ([]ReportMissedOrdersRow, error) {
	rows, err := q.db.Query(ctx, reportMissedOrders,
		arg.TenantID,
		arg.PeriodFrom,
		arg.PeriodTo,
		arg.ContractID,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ReportMissedOrdersRow
	for rows.Next() {
		var i ReportMissedOrdersRow
		if err := rows.Scan(&i.ObjectID, &i.ObjectName, &i.DueDate); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const reportObjectExecutions = `-- name: ReportObjectExecutions :many
SELECT wo.object_id, e.id AS execution_id, wo.due_date,
       e.device_finished_at, e.finished_at, u.display_name AS worker_name,
       (SELECT count(*) FROM work_execution_item i WHERE i.execution_id = e.id AND i.checked) AS checked_items,
       (SELECT count(*) FROM work_execution_item i WHERE i.execution_id = e.id) AS total_items
FROM work_execution e
JOIN work_order wo ON wo.id = e.work_order_id AND wo.tenant_id = e.tenant_id
JOIN app_user u ON u.id = e.worker_id
WHERE e.tenant_id = $1
  AND wo.due_date BETWEEN $2 AND $3
  AND e.device_finished_at IS NOT NULL
  AND ($4::uuid IS NULL
       OR EXISTS (SELECT 1 FROM object o WHERE o.id = wo.object_id AND o.contract_id = $4))
ORDER BY wo.object_id, e.device_finished_at
`

type ReportObjectExecutionsParams struct {
	TenantID   uuid.UUID
	PeriodFrom pgtype.Date
	PeriodTo   pgtype.Date
	ContractID uuid.NullUUID
}

type ReportObjectExecutionsRow struct {
	ObjectID         uuid.UUID
	ExecutionID      uuid.UUID
	DueDate          pgtype.Date
	DeviceFinishedAt pgtype.Timestamptz
	FinishedAt       pgtype.Timestamptz
	WorkerName       string
	CheckedItems     int64
	TotalItems       int64
}

func (q *Queries) ReportObjectExecutions(ctx context.Context, arg ReportObjectExecutionsParams) ([]ReportObjectExecutionsRow, error) {
	rows, err := q.db.Query(ctx, reportObjectExecutions,
		arg.TenantID,
		arg.PeriodFrom,
		arg.PeriodTo,
		arg.ContractID,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ReportObjectExecutionsRow
	for rows.Next() {
		var i ReportObjectExecutionsRow
		if err := rows.Scan(
			&i.ObjectID,
			&i.ExecutionID,
			&i.DueDate,
			&i.DeviceFinishedAt,
			&i.FinishedAt,
			&i.WorkerName,
			&i.CheckedItems,
			&i.TotalItems,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const reportSummaryRows = `-- name: ReportSummaryRows :many
SELECT o.id AS object_id, o.name AS object_name, o.address,
       count(wo.id) AS planned,
       count(wo.id) FILTER (WHERE wo.status = 'done') AS done,
       count(wo.id) FILTER (WHERE wo.status = 'missed') AS missed
FROM work_order wo
JOIN object o ON o.id = wo.object_id AND o.tenant_id = wo.tenant_id
WHERE wo.tenant_id = $1
  AND wo.due_date BETWEEN $2 AND $3
  AND ($4::uuid IS NULL OR o.contract_id = $4)
GROUP BY o.id, o.name, o.address
ORDER BY o.address NULLS LAST, o.name
`

type ReportSummaryRowsParams struct {
	TenantID   uuid.UUID
	PeriodFrom pgtype.Date
	PeriodTo   pgtype.Date
	ContractID uuid.NullUUID
}

type ReportSummaryRowsRow struct {
	ObjectID   uuid.UUID
	ObjectName string
	Address    *string
	Planned    int64
	Done       int64
	Missed     int64
}

func (q *Queries) ReportSummaryRows(ctx context.Context, arg ReportSummaryRowsParams) ([]ReportSummaryRowsRow, error) {
	rows, err := q.db.Query(ctx, reportSummaryRows,
		arg.TenantID,
		arg.PeriodFrom,
		arg.PeriodTo,
		arg.ContractID,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ReportSummaryRowsRow
	for rows.Next() {
		var i ReportSummaryRowsRow
		if err := rows.Scan(
			&i.ObjectID,
			&i.ObjectName,
			&i.Address,
			&i.Planned,
			&i.Done,
			&i.Missed,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
