// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: staff.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countActiveWorkersInTenant = `-- name: CountActiveWorkersInTenant :one
SELECT count(*) FROM app_user
WHERE tenant_id = $1 AND role = 'worker' AND is_active AND id = ANY($2::uuid[])
`

type CountActiveWorkersInTenantParams struct {
	TenantID uuid.UUID
	Ids      []uuid.UUID
}

func (q *Queries) CountActiveWorkersInTenant(ctx context.Context, arg CountActiveWorkersInTenantParams) (int64, error) {
	row := q.db.QueryRow(ctx, countActiveWorkersInTenant, arg.TenantID, arg.Ids)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countContractsInTenant = `-- name: CountContractsInTenant :one
SELECT count(*) FROM contract WHERE tenant_id = $1 AND id = ANY($2::uuid[])
`

type CountContractsInTenantParams struct {
	TenantID uuid.UUID
	Ids      []uuid.UUID
}

func (q *Queries) CountContractsInTenant(ctx context.Context, arg CountContractsInTenantParams) (int64, error) {
	row := q.db.QueryRow(ctx, countContractsInTenant, arg.TenantID, arg.Ids)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countObjectsInTenant = `-- name: CountObjectsInTenant :one
SELECT count(*) FROM object WHERE tenant_id = $1 AND id = ANY($2::uuid[])
`

type CountObjectsInTenantParams struct {
	TenantID uuid.UUID
	Ids      []uuid.UUID
}

func (q *Queries) CountObjectsInTenant(ctx context.Context, arg CountObjectsInTenantParams) (int64, error) {
	row := q.db.QueryRow(ctx, countObjectsInTenant, arg.TenantID, arg.Ids)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countVersionsInTenant = `-- name: CountVersionsInTenant :one
SELECT count(*) FROM checklist_template_version v
JOIN checklist_template t ON t.id = v.template_id
WHERE t.tenant_id = $1 AND v.id = ANY($2::uuid[])
`

type CountVersionsInTenantParams struct {
	TenantID uuid.UUID
	Ids      []uuid.UUID
}

func (q *Queries) CountVersionsInTenant(ctx context.Context, arg CountVersionsInTenantParams) (int64, error) {
	row := q.db.QueryRow(ctx, countVersionsInTenant, arg.TenantID, arg.Ids)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getExecutionDetail = `-- name: GetExecutionDetail :one

SELECT e.id, e.work_order_id, e.created_at, e.started_at, e.finished_at, e.device_finished_at, e.note,
       u.display_name AS worker_name,
       wo.object_id, o.name AS object_name
FROM work_execution e
JOIN app_user u ON u.id = e.worker_id
JOIN work_order wo ON wo.id = e.work_order_id AND wo.tenant_id = e.tenant_id
JOIN object o ON o.id = wo.object_id AND o.tenant_id = e.tenant_id
WHERE e.id = $1 AND e.tenant_id = $2
`

type GetExecutionDetailParams struct {
	ID       uuid.UUID
	TenantID uuid.UUID
}

type GetExecutionDetailRow struct {
	ID               uuid.UUID
	WorkOrderID      uuid.UUID
	CreatedAt        pgtype.Timestamptz
	StartedAt        pgtype.Timestamptz
	FinishedAt       pgtype.Timestamptz
	DeviceFinishedAt pgtype.Timestamptz
	Note             *string
	WorkerName       string
	ObjectID         uuid.UUID
	ObjectName       string
}

// === evidence reads ========================================================
func (q *Queries) GetExecutionDetail(ctx context.Context, arg GetExecutionDetailParams) (GetExecutionDetailRow, error) {
	row := q.db.QueryRow(ctx, getExecutionDetail, arg.ID, arg.TenantID)
	var i GetExecutionDetailRow
	err := row.Scan(
		&i.ID,
		&i.WorkOrderID,
		&i.CreatedAt,
		&i.StartedAt,
		&i.FinishedAt,
		&i.DeviceFinishedAt,
		&i.Note,
		&i.WorkerName,
		&i.ObjectID,
		&i.ObjectName,
	)
	return i, err
}

const getObject = `-- name: GetObject :one
SELECT id, name, address, lat, lon, kind, qr_token, contract_id, is_active, created_at
FROM object WHERE id = $1 AND tenant_id = $2
`

type GetObjectParams struct {
	ID       uuid.UUID
	TenantID uuid.UUID
}

type GetObjectRow struct {
	ID         uuid.UUID
	Name       string
	Address    *string
	Lat        *float64
	Lon        *float64
	Kind       *string
	QrToken    *string
	ContractID uuid.NullUUID
	IsActive   bool
	CreatedAt  pgtype.Timestamptz
}

func (q *Queries) GetObject(ctx context.Context, arg GetObjectParams) (GetObjectRow, error) {
	row := q.db.QueryRow(ctx, getObject, arg.ID, arg.TenantID)
	var i GetObjectRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Address,
		&i.Lat,
		&i.Lon,
		&i.Kind,
		&i.QrToken,
		&i.ContractID,
		&i.IsActive,
		&i.CreatedAt,
	)
	return i, err
}

const getPhotoForStaff = `-- name: GetPhotoForStaff :one
SELECT id, execution_id, kind, s3_key, taken_at, lat, lon, uploaded_at
FROM photo WHERE id = $1 AND tenant_id = $2
`

type GetPhotoForStaffParams struct {
	ID       uuid.UUID
	TenantID uuid.UUID
}

type GetPhotoForStaffRow struct {
	ID          uuid.UUID
	ExecutionID uuid.NullUUID
	Kind        PhotoKind
	S3Key       string
	TakenAt     pgtype.Timestamptz
	Lat         *float64
	Lon         *float64
	UploadedAt  pgtype.Timestamptz
}

func (q *Queries) GetPhotoForStaff(ctx context.Context, arg GetPhotoForStaffParams) (GetPhotoForStaffRow, error) {
	row := q.db.QueryRow(ctx, getPhotoForStaff, arg.ID, arg.TenantID)
	var i GetPhotoForStaffRow
	err := row.Scan(
		&i.ID,
		&i.ExecutionID,
		&i.Kind,
		&i.S3Key,
		&i.TakenAt,
		&i.Lat,
		&i.Lon,
		&i.UploadedAt,
	)
	return i, err
}

const getWorkOrder = `-- name: GetWorkOrder :one
SELECT id, object_id, version_id, assignee_id, due_date, status, created_at
FROM work_order WHERE id = $1 AND tenant_id = $2
`

type GetWorkOrderParams struct {
	ID       uuid.UUID
	TenantID uuid.UUID
}

type GetWorkOrderRow struct {
	ID         uuid.UUID
	ObjectID   uuid.UUID
	VersionID  uuid.UUID
	AssigneeID uuid.NullUUID
	DueDate    pgtype.Date
	Status     WorkOrderStatus
	CreatedAt  pgtype.Timestamptz
}

func (q *Queries) GetWorkOrder(ctx context.Context, arg GetWorkOrderParams) (GetWorkOrderRow, error) {
	row := q.db.QueryRow(ctx, getWorkOrder, arg.ID, arg.TenantID)
	var i GetWorkOrderRow
	err := row.Scan(
		&i.ID,
		&i.ObjectID,
		&i.VersionID,
		&i.AssigneeID,
		&i.DueDate,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const getWorker = `-- name: GetWorker :one
SELECT id, display_name, is_active, created_at
FROM app_user WHERE id = $1 AND tenant_id = $2 AND role = 'worker'
`

type GetWorkerParams struct {
	ID       uuid.UUID
	TenantID uuid.UUID
}

type GetWorkerRow struct {
	ID          uuid.UUID
	DisplayName string
	IsActive    bool
	CreatedAt   pgtype.Timestamptz
}

func (q *Queries) GetWorker(ctx context.Context, arg GetWorkerParams) (GetWorkerRow, error) {
	row := q.db.QueryRow(ctx, getWorker, arg.ID, arg.TenantID)
	var i GetWorkerRow
	err := row.Scan(
		&i.ID,
		&i.DisplayName,
		&i.IsActive,
		&i.CreatedAt,
	)
	return i, err
}

const insertInvite = `-- name: InsertInvite :exec
INSERT INTO worker_invite (tenant_id, user_id, code, expires_at)
VALUES ($1, $2, $3, $4)
`

type InsertInviteParams struct {
	TenantID  uuid.UUID
	UserID    uuid.UUID
	Code      string
	ExpiresAt pgtype.Timestamptz
}

func (q *Queries) InsertInvite(ctx context.Context, arg InsertInviteParams) error {
	_, err := q.db.Exec(ctx, insertInvite,
		arg.TenantID,
		arg.UserID,
		arg.Code,
		arg.ExpiresAt,
	)
	return err
}

const insertObject = `-- name: InsertObject :one

INSERT INTO object (tenant_id, name, address, lat, lon, kind, qr_token, contract_id)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, name, address, lat, lon, kind, qr_token, contract_id, is_active, created_at
`

type InsertObjectParams struct {
	TenantID   uuid.UUID
	Name       string
	Address    *string
	Lat        *float64
	Lon        *float64
	Kind       *string
	QrToken    *string
	ContractID uuid.NullUUID
}

type InsertObjectRow struct {
	ID         uuid.UUID
	Name       string
	Address    *string
	Lat        *float64
	Lon        *float64
	Kind       *string
	QrToken    *string
	ContractID uuid.NullUUID
	IsActive   bool
	CreatedAt  pgtype.Timestamptz
}

// === objects ===============================================================
func (q *Queries) InsertObject(ctx context.Context, arg InsertObjectParams) (InsertObjectRow, error) {
	row := q.db.QueryRow(ctx, insertObject,
		arg.TenantID,
		arg.Name,
		arg.Address,
		arg.Lat,
		arg.Lon,
		arg.Kind,
		arg.QrToken,
		arg.ContractID,
	)
	var i InsertObjectRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Address,
		&i.Lat,
		&i.Lon,
		&i.Kind,
		&i.QrToken,
		&i.ContractID,
		&i.IsActive,
		&i.CreatedAt,
	)
	return i, err
}

const insertWorkOrder = `-- name: InsertWorkOrder :exec

INSERT INTO work_order (id, tenant_id, object_id, version_id, assignee_id, due_date)
VALUES ($1, $2, $3, $4, $5, $6)
`

type InsertWorkOrderParams struct {
	ID         uuid.UUID
	TenantID   uuid.UUID
	ObjectID   uuid.UUID
	VersionID  uuid.UUID
	AssigneeID uuid.NullUUID
	DueDate    pgtype.Date
}

// === work orders ===========================================================
func (q *Queries) InsertWorkOrder(ctx context.Context, arg InsertWorkOrderParams) error {
	_, err := q.db.Exec(ctx, insertWorkOrder,
		arg.ID,
		arg.TenantID,
		arg.ObjectID,
		arg.VersionID,
		arg.AssigneeID,
		arg.DueDate,
	)
	return err
}

const insertWorker = `-- name: InsertWorker :one
INSERT INTO app_user (tenant_id, role, display_name)
VALUES ($1, 'worker', $2)
RETURNING id, display_name, is_active, created_at
`

type InsertWorkerParams struct {
	TenantID    uuid.UUID
	DisplayName string
}

type InsertWorkerRow struct {
	ID          uuid.UUID
	DisplayName string
	IsActive    bool
	CreatedAt   pgtype.Timestamptz
}

func (q *Queries) InsertWorker(ctx context.Context, arg InsertWorkerParams) (InsertWorkerRow, error) {
	row := q.db.QueryRow(ctx, insertWorker, arg.TenantID, arg.DisplayName)
	var i InsertWorkerRow
	err := row.Scan(
		&i.ID,
		&i.DisplayName,
		&i.IsActive,
		&i.CreatedAt,
	)
	return i, err
}

const listDashboardOrders = `-- name: ListDashboardOrders :many

SELECT order_id, status, due_date, object_id, object_name, address, lat, lon, worker_name, last_finished_at, last_activity_at, photo_count FROM (
    SELECT DISTINCT ON (wo.id)
        wo.id AS order_id, wo.status, wo.due_date,
        o.id AS object_id, o.name AS object_name, o.address, o.lat, o.lon,
        u.display_name AS worker_name, e.finished_at AS last_finished_at, e.created_at AS last_activity_at,
        (SELECT count(*) FROM photo p WHERE p.execution_id = e.id AND p.uploaded_at IS NOT NULL) AS photo_count
    FROM work_order wo
    JOIN object o ON o.id = wo.object_id AND o.tenant_id = wo.tenant_id
    LEFT JOIN work_execution e ON e.work_order_id = wo.id AND e.tenant_id = wo.tenant_id
    LEFT JOIN app_user u ON u.id = e.worker_id
    WHERE wo.tenant_id = $1 AND wo.due_date = $2
    ORDER BY wo.id, e.created_at DESC NULLS LAST
) sub
ORDER BY object_name
`

type ListDashboardOrdersParams struct {
	TenantID uuid.UUID
	DueDate  pgtype.Date
}

type ListDashboardOrdersRow struct {
	OrderID        uuid.UUID
	Status         WorkOrderStatus
	DueDate        pgtype.Date
	ObjectID       uuid.UUID
	ObjectName     string
	Address        *string
	Lat            *float64
	Lon            *float64
	WorkerName     *string
	LastFinishedAt pgtype.Timestamptz
	LastActivityAt pgtype.Timestamptz
	PhotoCount     int64
}

// === dashboard =============================================================
// Same LEFT-JOIN-through-a-derived-table nullability gap as ListWorkers:
// worker_name must come from a directly-joined base table (app_user) for
// sqlc to type it *string instead of a NOT NULL string that panics on scan
// when a work order has no execution yet. work_execution is also joined
// directly so finished_at/created_at nullability is unambiguous. DISTINCT ON
// picks the single latest execution per order; the photo-count correlated
// subquery naturally yields 0 (not NULL) when e.id is NULL, so no COALESCE
// is needed. The outer SELECT re-sorts by object_name.
func (q *Queries) ListDashboardOrders(ctx context.Context, arg ListDashboardOrdersParams) ([]ListDashboardOrdersRow, error) {
	rows, err := q.db.Query(ctx, listDashboardOrders, arg.TenantID, arg.DueDate)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListDashboardOrdersRow
	for rows.Next() {
		var i ListDashboardOrdersRow
		if err := rows.Scan(
			&i.OrderID,
			&i.Status,
			&i.DueDate,
			&i.ObjectID,
			&i.ObjectName,
			&i.Address,
			&i.Lat,
			&i.Lon,
			&i.WorkerName,
			&i.LastFinishedAt,
			&i.LastActivityAt,
			&i.PhotoCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listExecutionItemsWithTitles = `-- name: ListExecutionItemsWithTitles :many
SELECT ei.id, ei.template_item_id, ei.checked, ei.checked_at, ti.position, ti.title
FROM work_execution_item ei
JOIN checklist_template_item ti ON ti.id = ei.template_item_id
WHERE ei.execution_id = $1
ORDER BY ti.position
`

type ListExecutionItemsWithTitlesRow struct {
	ID             uuid.UUID
	TemplateItemID uuid.UUID
	Checked        bool
	CheckedAt      pgtype.Timestamptz
	Position       int32
	Title          string
}

func (q *Queries) ListExecutionItemsWithTitles(ctx context.Context, executionID uuid.UUID) ([]ListExecutionItemsWithTitlesRow, error) {
	rows, err := q.db.Query(ctx, listExecutionItemsWithTitles, executionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListExecutionItemsWithTitlesRow
	for rows.Next() {
		var i ListExecutionItemsWithTitlesRow
		if err := rows.Scan(
			&i.ID,
			&i.TemplateItemID,
			&i.Checked,
			&i.CheckedAt,
			&i.Position,
			&i.Title,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listObjectExecutions = `-- name: ListObjectExecutions :many
SELECT e.id, e.work_order_id, e.created_at, e.started_at, e.finished_at, e.device_finished_at,
       u.display_name AS worker_name,
       (SELECT count(*) FROM photo p WHERE p.execution_id = e.id AND p.uploaded_at IS NOT NULL) AS photo_count
FROM work_execution e
JOIN work_order wo ON wo.id = e.work_order_id AND wo.tenant_id = e.tenant_id
JOIN app_user u ON u.id = e.worker_id
WHERE e.tenant_id = $1 AND wo.object_id = $2
  AND (e.created_at, e.id) < ($3::timestamptz, $4::uuid)
ORDER BY e.created_at DESC, e.id DESC
LIMIT $5
`

type ListObjectExecutionsParams struct {
	TenantID       uuid.UUID
	ObjectID       uuid.UUID
	AfterCreatedAt pgtype.Timestamptz
	AfterID        uuid.UUID
	PageLimit      int32
}

type ListObjectExecutionsRow struct {
	ID               uuid.UUID
	WorkOrderID      uuid.UUID
	CreatedAt        pgtype.Timestamptz
	StartedAt        pgtype.Timestamptz
	FinishedAt       pgtype.Timestamptz
	DeviceFinishedAt pgtype.Timestamptz
	WorkerName       string
	PhotoCount       int64
}

func (q *Queries) ListObjectExecutions(ctx context.Context, arg ListObjectExecutionsParams) ([]ListObjectExecutionsRow, error) {
	rows, err := q.db.Query(ctx, listObjectExecutions,
		arg.TenantID,
		arg.ObjectID,
		arg.AfterCreatedAt,
		arg.AfterID,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListObjectExecutionsRow
	for rows.Next() {
		var i ListObjectExecutionsRow
		if err := rows.Scan(
			&i.ID,
			&i.WorkOrderID,
			&i.CreatedAt,
			&i.StartedAt,
			&i.FinishedAt,
			&i.DeviceFinishedAt,
			&i.WorkerName,
			&i.PhotoCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWorkOrders = `-- name: ListWorkOrders :many
SELECT id, object_id, version_id, assignee_id, due_date, status, created_at
FROM work_order
WHERE tenant_id = $1
  AND ($2::date IS NULL OR due_date = $2)
  AND ($3::uuid IS NULL OR object_id = $3)
  AND ($4::uuid IS NULL OR assignee_id = $4)
  AND ($5::work_order_status IS NULL OR status = $5)
ORDER BY due_date DESC, created_at DESC
LIMIT 500
`

type ListWorkOrdersParams struct {
	TenantID   uuid.UUID
	DueDate    pgtype.Date
	ObjectID   uuid.NullUUID
	AssigneeID uuid.NullUUID
	Status     *WorkOrderStatus
}

type ListWorkOrdersRow struct {
	ID         uuid.UUID
	ObjectID   uuid.UUID
	VersionID  uuid.UUID
	AssigneeID uuid.NullUUID
	DueDate    pgtype.Date
	Status     WorkOrderStatus
	CreatedAt  pgtype.Timestamptz
}

func (q *Queries) ListWorkOrders(ctx context.Context, arg ListWorkOrdersParams) ([]ListWorkOrdersRow, error) {
	rows, err := q.db.Query(ctx, listWorkOrders,
		arg.TenantID,
		arg.DueDate,
		arg.ObjectID,
		arg.AssigneeID,
		arg.Status,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListWorkOrdersRow
	for rows.Next() {
		var i ListWorkOrdersRow
		if err := rows.Scan(
			&i.ID,
			&i.ObjectID,
			&i.VersionID,
			&i.AssigneeID,
			&i.DueDate,
			&i.Status,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWorkers = `-- name: ListWorkers :many

SELECT id, display_name, is_active, created_at, pending_code, pending_expires_at FROM (
    SELECT DISTINCT ON (u.id) u.id, u.display_name, u.is_active, u.created_at,
           wi.code AS pending_code, wi.expires_at AS pending_expires_at
    FROM app_user u
    LEFT JOIN worker_invite wi ON wi.user_id = u.id AND wi.used_at IS NULL AND wi.expires_at > now()
    WHERE u.tenant_id = $1 AND u.role = 'worker'
    ORDER BY u.id, wi.expires_at DESC NULLS LAST
) sub
ORDER BY display_name
`

type ListWorkersRow struct {
	ID               uuid.UUID
	DisplayName      string
	IsActive         bool
	CreatedAt        pgtype.Timestamptz
	PendingCode      *string
	PendingExpiresAt pgtype.Timestamptz
}

// === workers & invites =====================================================
// sqlc (v1.31.1) does not propagate LEFT JOIN nullability through a derived
// table/LATERAL: pending_code/pending_expires_at would be typed as NOT NULL
// (Go string, not *string) even though most workers have no pending invite,
// and pgx panics scanning SQL NULL into a non-nullable string. Joining
// worker_invite directly (a real table) lets sqlc infer nullability
// correctly; DISTINCT ON collapses to the single latest unused invite per
// worker, and the outer SELECT re-sorts by display_name since DISTINCT ON's
// ORDER BY must lead with the distinct key (u.id).
func (q *Queries) ListWorkers(ctx context.Context, tenantID uuid.UUID) ([]ListWorkersRow, error) {
	rows, err := q.db.Query(ctx, listWorkers, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListWorkersRow
	for rows.Next() {
		var i ListWorkersRow
		if err := rows.Scan(
			&i.ID,
			&i.DisplayName,
			&i.IsActive,
			&i.CreatedAt,
			&i.PendingCode,
			&i.PendingExpiresAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeWorkerDeviceTokens = `-- name: RevokeWorkerDeviceTokens :exec
UPDATE device_token SET revoked_at = now()
WHERE tenant_id = $1 AND user_id = $2 AND revoked_at IS NULL
`

type RevokeWorkerDeviceTokensParams struct {
	TenantID uuid.UUID
	UserID   uuid.UUID
}

func (q *Queries) RevokeWorkerDeviceTokens(ctx context.Context, arg RevokeWorkerDeviceTokensParams) error {
	_, err := q.db.Exec(ctx, revokeWorkerDeviceTokens, arg.TenantID, arg.UserID)
	return err
}

const updateObject = `-- name: UpdateObject :one
UPDATE object SET
    name        = COALESCE($1, name),
    address     = COALESCE($2, address),
    lat         = COALESCE($3, lat),
    lon         = COALESCE($4, lon),
    kind        = COALESCE($5, kind),
    qr_token    = COALESCE($6, qr_token),
    contract_id = COALESCE($7, contract_id),
    is_active   = COALESCE($8, is_active)
WHERE id = $9 AND tenant_id = $10
RETURNING id, name, address, lat, lon, kind, qr_token, contract_id, is_active, created_at
`

type UpdateObjectParams struct {
	Name       *string
	Address    *string
	Lat        *float64
	Lon        *float64
	Kind       *string
	QrToken    *string
	ContractID uuid.NullUUID
	IsActive   *bool
	ID         uuid.UUID
	TenantID   uuid.UUID
}

type UpdateObjectRow struct {
	ID         uuid.UUID
	Name       string
	Address    *string
	Lat        *float64
	Lon        *float64
	Kind       *string
	QrToken    *string
	ContractID uuid.NullUUID
	IsActive   bool
	CreatedAt  pgtype.Timestamptz
}

func (q *Queries) UpdateObject(ctx context.Context, arg UpdateObjectParams) (UpdateObjectRow, error) {
	row := q.db.QueryRow(ctx, updateObject,
		arg.Name,
		arg.Address,
		arg.Lat,
		arg.Lon,
		arg.Kind,
		arg.QrToken,
		arg.ContractID,
		arg.IsActive,
		arg.ID,
		arg.TenantID,
	)
	var i UpdateObjectRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Address,
		&i.Lat,
		&i.Lon,
		&i.Kind,
		&i.QrToken,
		&i.ContractID,
		&i.IsActive,
		&i.CreatedAt,
	)
	return i, err
}

const updateWorkOrder = `-- name: UpdateWorkOrder :one
UPDATE work_order SET
    assignee_id = COALESCE($1, assignee_id),
    due_date    = COALESCE($2, due_date)
WHERE id = $3 AND tenant_id = $4
RETURNING id, object_id, version_id, assignee_id, due_date, status, created_at
`

type UpdateWorkOrderParams struct {
	AssigneeID uuid.NullUUID
	DueDate    pgtype.Date
	ID         uuid.UUID
	TenantID   uuid.UUID
}

type UpdateWorkOrderRow struct {
	ID         uuid.UUID
	ObjectID   uuid.UUID
	VersionID  uuid.UUID
	AssigneeID uuid.NullUUID
	DueDate    pgtype.Date
	Status     WorkOrderStatus
	CreatedAt  pgtype.Timestamptz
}

func (q *Queries) UpdateWorkOrder(ctx context.Context, arg UpdateWorkOrderParams) (UpdateWorkOrderRow, error) {
	row := q.db.QueryRow(ctx, updateWorkOrder,
		arg.AssigneeID,
		arg.DueDate,
		arg.ID,
		arg.TenantID,
	)
	var i UpdateWorkOrderRow
	err := row.Scan(
		&i.ID,
		&i.ObjectID,
		&i.VersionID,
		&i.AssigneeID,
		&i.DueDate,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const updateWorker = `-- name: UpdateWorker :one
UPDATE app_user SET
    display_name = COALESCE($1, display_name),
    is_active    = COALESCE($2, is_active)
WHERE id = $3 AND tenant_id = $4 AND role = 'worker'
RETURNING id, display_name, is_active, created_at
`

type UpdateWorkerParams struct {
	DisplayName *string
	IsActive    *bool
	ID          uuid.UUID
	TenantID    uuid.UUID
}

type UpdateWorkerRow struct {
	ID          uuid.UUID
	DisplayName string
	IsActive    bool
	CreatedAt   pgtype.Timestamptz
}

func (q *Queries) UpdateWorker(ctx context.Context, arg UpdateWorkerParams) (UpdateWorkerRow, error) {
	row := q.db.QueryRow(ctx, updateWorker,
		arg.DisplayName,
		arg.IsActive,
		arg.ID,
		arg.TenantID,
	)
	var i UpdateWorkerRow
	err := row.Scan(
		&i.ID,
		&i.DisplayName,
		&i.IsActive,
		&i.CreatedAt,
	)
	return i, err
}

const voidWorkerInvites = `-- name: VoidWorkerInvites :exec
UPDATE worker_invite SET used_at = now()
WHERE tenant_id = $1 AND user_id = $2 AND used_at IS NULL
`

type VoidWorkerInvitesParams struct {
	TenantID uuid.UUID
	UserID   uuid.UUID
}

func (q *Queries) VoidWorkerInvites(ctx context.Context, arg VoidWorkerInvitesParams) error {
	_, err := q.db.Exec(ctx, voidWorkerInvites, arg.TenantID, arg.UserID)
	return err
}
