// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: worker.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const confirmPhoto = `-- name: ConfirmPhoto :exec
UPDATE photo
SET uploaded_at = COALESCE(uploaded_at, now()),
    taken_at    = COALESCE(taken_at, $3),
    lat         = COALESCE(lat, $4),
    lon         = COALESCE(lon, $5)
WHERE id = $1 AND tenant_id = $2
`

type ConfirmPhotoParams struct {
	ID       uuid.UUID
	TenantID uuid.UUID
	TakenAt  pgtype.Timestamptz
	Lat      *float64
	Lon      *float64
}

// uploaded_at, taken_at, lat, lon are all stamped once (COALESCE): evidence
// is immutable, so a re-confirm replay cannot overwrite already-set values.
func (q *Queries) ConfirmPhoto(ctx context.Context, arg ConfirmPhotoParams) error {
	_, err := q.db.Exec(ctx, confirmPhoto,
		arg.ID,
		arg.TenantID,
		arg.TakenAt,
		arg.Lat,
		arg.Lon,
	)
	return err
}

const deleteExecutionItemsNotIn = `-- name: DeleteExecutionItemsNotIn :exec
DELETE FROM work_execution_item
WHERE execution_id = $1 AND id <> ALL($2::uuid[])
`

type DeleteExecutionItemsNotInParams struct {
	ExecutionID uuid.UUID
	KeepIds     []uuid.UUID
}

func (q *Queries) DeleteExecutionItemsNotIn(ctx context.Context, arg DeleteExecutionItemsNotInParams) error {
	_, err := q.db.Exec(ctx, deleteExecutionItemsNotIn, arg.ExecutionID, arg.KeepIds)
	return err
}

const getExecution = `-- name: GetExecution :one

SELECT id, work_order_id, worker_id, started_at, finished_at, device_finished_at, note
FROM work_execution
WHERE id = $1 AND tenant_id = $2
`

type GetExecutionParams struct {
	ID       uuid.UUID
	TenantID uuid.UUID
}

type GetExecutionRow struct {
	ID               uuid.UUID
	WorkOrderID      uuid.UUID
	WorkerID         uuid.UUID
	StartedAt        pgtype.Timestamptz
	FinishedAt       pgtype.Timestamptz
	DeviceFinishedAt pgtype.Timestamptz
	Note             *string
}

// === execution read (server view) ==========================================
func (q *Queries) GetExecution(ctx context.Context, arg GetExecutionParams) (GetExecutionRow, error) {
	row := q.db.QueryRow(ctx, getExecution, arg.ID, arg.TenantID)
	var i GetExecutionRow
	err := row.Scan(
		&i.ID,
		&i.WorkOrderID,
		&i.WorkerID,
		&i.StartedAt,
		&i.FinishedAt,
		&i.DeviceFinishedAt,
		&i.Note,
	)
	return i, err
}

const getExecutionForWorker = `-- name: GetExecutionForWorker :one
SELECT id, tenant_id, worker_id
FROM work_execution
WHERE id = $1 AND tenant_id = $2
`

type GetExecutionForWorkerParams struct {
	ID       uuid.UUID
	TenantID uuid.UUID
}

type GetExecutionForWorkerRow struct {
	ID       uuid.UUID
	TenantID uuid.UUID
	WorkerID uuid.UUID
}

func (q *Queries) GetExecutionForWorker(ctx context.Context, arg GetExecutionForWorkerParams) (GetExecutionForWorkerRow, error) {
	row := q.db.QueryRow(ctx, getExecutionForWorker, arg.ID, arg.TenantID)
	var i GetExecutionForWorkerRow
	err := row.Scan(&i.ID, &i.TenantID, &i.WorkerID)
	return i, err
}

const getObjectByQr = `-- name: GetObjectByQr :one

SELECT id, name, address, lat, lon, kind, qr_token, is_active
FROM object
WHERE tenant_id = $1 AND qr_token = $2 AND is_active
`

type GetObjectByQrParams struct {
	TenantID uuid.UUID
	QrToken  *string
}

type GetObjectByQrRow struct {
	ID       uuid.UUID
	Name     string
	Address  *string
	Lat      *float64
	Lon      *float64
	Kind     *string
	QrToken  *string
	IsActive bool
}

// === QR resolution =========================================================
func (q *Queries) GetObjectByQr(ctx context.Context, arg GetObjectByQrParams) (GetObjectByQrRow, error) {
	row := q.db.QueryRow(ctx, getObjectByQr, arg.TenantID, arg.QrToken)
	var i GetObjectByQrRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Address,
		&i.Lat,
		&i.Lon,
		&i.Kind,
		&i.QrToken,
		&i.IsActive,
	)
	return i, err
}

const getPhoto = `-- name: GetPhoto :one
SELECT id, tenant_id, execution_id, kind, s3_key, taken_at, lat, lon, uploaded_at
FROM photo
WHERE id = $1 AND tenant_id = $2
`

type GetPhotoParams struct {
	ID       uuid.UUID
	TenantID uuid.UUID
}

type GetPhotoRow struct {
	ID          uuid.UUID
	TenantID    uuid.UUID
	ExecutionID uuid.NullUUID
	Kind        PhotoKind
	S3Key       string
	TakenAt     pgtype.Timestamptz
	Lat         *float64
	Lon         *float64
	UploadedAt  pgtype.Timestamptz
}

func (q *Queries) GetPhoto(ctx context.Context, arg GetPhotoParams) (GetPhotoRow, error) {
	row := q.db.QueryRow(ctx, getPhoto, arg.ID, arg.TenantID)
	var i GetPhotoRow
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.ExecutionID,
		&i.Kind,
		&i.S3Key,
		&i.TakenAt,
		&i.Lat,
		&i.Lon,
		&i.UploadedAt,
	)
	return i, err
}

const getTenantTimezone = `-- name: GetTenantTimezone :one

SELECT timezone FROM tenant WHERE id = $1
`

// === tenant settings ========================================================
func (q *Queries) GetTenantTimezone(ctx context.Context, id uuid.UUID) (string, error) {
	row := q.db.QueryRow(ctx, getTenantTimezone, id)
	var timezone string
	err := row.Scan(&timezone)
	return timezone, err
}

const getWorkOrderForWorker = `-- name: GetWorkOrderForWorker :one

SELECT id, object_id, assignee_id, status, version_id
FROM work_order
WHERE id = $1 AND tenant_id = $2
FOR UPDATE
`

type GetWorkOrderForWorkerParams struct {
	ID       uuid.UUID
	TenantID uuid.UUID
}

type GetWorkOrderForWorkerRow struct {
	ID         uuid.UUID
	ObjectID   uuid.UUID
	AssigneeID uuid.NullUUID
	Status     WorkOrderStatus
	VersionID  uuid.UUID
}

// === execution upsert ======================================================
// Locked: called inside UpsertExecution's transaction so the assignment
// check and the rest of the upsert share one row lock on work_order. This
// serializes a concurrent staff reassignment (UpdateWorkOrder) against an
// in-flight worker upsert instead of letting both interleave and leave the
// execution bound to a worker who is no longer assigned.
// FOR UPDATE (not FOR SHARE): the same transaction later UPDATEs this row
// (SetWorkOrderStatus); a shared lock would deadlock two concurrent upserts
// of the same order on lock upgrade. Exclusive from the start serializes them.
func (q *Queries) GetWorkOrderForWorker(ctx context.Context, arg GetWorkOrderForWorkerParams) (GetWorkOrderForWorkerRow, error) {
	row := q.db.QueryRow(ctx, getWorkOrderForWorker, arg.ID, arg.TenantID)
	var i GetWorkOrderForWorkerRow
	err := row.Scan(
		&i.ID,
		&i.ObjectID,
		&i.AssigneeID,
		&i.Status,
		&i.VersionID,
	)
	return i, err
}

const getWorkerOrderForObject = `-- name: GetWorkerOrderForObject :one
SELECT id, object_id, due_date, status, version_id
FROM work_order
WHERE tenant_id = $1 AND assignee_id = $2 AND object_id = $3 AND due_date = $4
ORDER BY created_at DESC
LIMIT 1
`

type GetWorkerOrderForObjectParams struct {
	TenantID   uuid.UUID
	AssigneeID uuid.NullUUID
	ObjectID   uuid.UUID
	DueDate    pgtype.Date
}

type GetWorkerOrderForObjectRow struct {
	ID        uuid.UUID
	ObjectID  uuid.UUID
	DueDate   pgtype.Date
	Status    WorkOrderStatus
	VersionID uuid.UUID
}

func (q *Queries) GetWorkerOrderForObject(ctx context.Context, arg GetWorkerOrderForObjectParams) (GetWorkerOrderForObjectRow, error) {
	row := q.db.QueryRow(ctx, getWorkerOrderForObject,
		arg.TenantID,
		arg.AssigneeID,
		arg.ObjectID,
		arg.DueDate,
	)
	var i GetWorkerOrderForObjectRow
	err := row.Scan(
		&i.ID,
		&i.ObjectID,
		&i.DueDate,
		&i.Status,
		&i.VersionID,
	)
	return i, err
}

const insertPhotoPresign = `-- name: InsertPhotoPresign :exec

INSERT INTO photo (id, tenant_id, execution_id, kind, s3_key)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (id) DO NOTHING
`

type InsertPhotoPresignParams struct {
	ID          uuid.UUID
	TenantID    uuid.UUID
	ExecutionID uuid.NullUUID
	Kind        PhotoKind
	S3Key       string
}

// === photos (two-phase) ====================================================
func (q *Queries) InsertPhotoPresign(ctx context.Context, arg InsertPhotoPresignParams) error {
	_, err := q.db.Exec(ctx, insertPhotoPresign,
		arg.ID,
		arg.TenantID,
		arg.ExecutionID,
		arg.Kind,
		arg.S3Key,
	)
	return err
}

const listChecklistItemsByVersions = `-- name: ListChecklistItemsByVersions :many
SELECT i.version_id, i.id, i.position, i.title, i.requires_photo
FROM checklist_template_item i
JOIN checklist_template_version v ON v.id = i.version_id
JOIN checklist_template t ON t.id = v.template_id
WHERE i.version_id = ANY($1::uuid[])
  AND t.tenant_id = $2
ORDER BY i.version_id, i.position
`

type ListChecklistItemsByVersionsParams struct {
	VersionIds []uuid.UUID
	TenantID   uuid.UUID
}

type ListChecklistItemsByVersionsRow struct {
	VersionID     uuid.UUID
	ID            uuid.UUID
	Position      int32
	Title         string
	RequiresPhoto bool
}

func (q *Queries) ListChecklistItemsByVersions(ctx context.Context, arg ListChecklistItemsByVersionsParams) ([]ListChecklistItemsByVersionsRow, error) {
	rows, err := q.db.Query(ctx, listChecklistItemsByVersions, arg.VersionIds, arg.TenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListChecklistItemsByVersionsRow
	for rows.Next() {
		var i ListChecklistItemsByVersionsRow
		if err := rows.Scan(
			&i.VersionID,
			&i.ID,
			&i.Position,
			&i.Title,
			&i.RequiresPhoto,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listExecutionItems = `-- name: ListExecutionItems :many
SELECT id, template_item_id, checked, checked_at
FROM work_execution_item
WHERE execution_id = $1
ORDER BY id
`

type ListExecutionItemsRow struct {
	ID             uuid.UUID
	TemplateItemID uuid.UUID
	Checked        bool
	CheckedAt      pgtype.Timestamptz
}

func (q *Queries) ListExecutionItems(ctx context.Context, executionID uuid.UUID) ([]ListExecutionItemsRow, error) {
	rows, err := q.db.Query(ctx, listExecutionItems, executionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListExecutionItemsRow
	for rows.Next() {
		var i ListExecutionItemsRow
		if err := rows.Scan(
			&i.ID,
			&i.TemplateItemID,
			&i.Checked,
			&i.CheckedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listExecutionPhotos = `-- name: ListExecutionPhotos :many
SELECT id, kind, s3_key, taken_at, lat, lon, uploaded_at
FROM photo
WHERE execution_id = $1 AND tenant_id = $2
ORDER BY id
`

type ListExecutionPhotosParams struct {
	ExecutionID uuid.NullUUID
	TenantID    uuid.UUID
}

type ListExecutionPhotosRow struct {
	ID         uuid.UUID
	Kind       PhotoKind
	S3Key      string
	TakenAt    pgtype.Timestamptz
	Lat        *float64
	Lon        *float64
	UploadedAt pgtype.Timestamptz
}

func (q *Queries) ListExecutionPhotos(ctx context.Context, arg ListExecutionPhotosParams) ([]ListExecutionPhotosRow, error) {
	rows, err := q.db.Query(ctx, listExecutionPhotos, arg.ExecutionID, arg.TenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListExecutionPhotosRow
	for rows.Next() {
		var i ListExecutionPhotosRow
		if err := rows.Scan(
			&i.ID,
			&i.Kind,
			&i.S3Key,
			&i.TakenAt,
			&i.Lat,
			&i.Lon,
			&i.UploadedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWorkerTodayOrders = `-- name: ListWorkerTodayOrders :many

SELECT wo.id, wo.object_id, wo.due_date, wo.status, wo.version_id,
       o.name AS object_name, o.address, o.lat, o.lon, o.qr_token
FROM work_order wo
JOIN object o ON o.id = wo.object_id AND o.tenant_id = wo.tenant_id
WHERE wo.tenant_id = $1 AND wo.assignee_id = $2 AND wo.due_date = $3
ORDER BY o.name
`

type ListWorkerTodayOrdersParams struct {
	TenantID   uuid.UUID
	AssigneeID uuid.NullUUID
	DueDate    pgtype.Date
}

type ListWorkerTodayOrdersRow struct {
	ID         uuid.UUID
	ObjectID   uuid.UUID
	DueDate    pgtype.Date
	Status     WorkOrderStatus
	VersionID  uuid.UUID
	ObjectName string
	Address    *string
	Lat        *float64
	Lon        *float64
	QrToken    *string
}

// === today bootstrap =======================================================
func (q *Queries) ListWorkerTodayOrders(ctx context.Context, arg ListWorkerTodayOrdersParams) ([]ListWorkerTodayOrdersRow, error) {
	rows, err := q.db.Query(ctx, listWorkerTodayOrders, arg.TenantID, arg.AssigneeID, arg.DueDate)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListWorkerTodayOrdersRow
	for rows.Next() {
		var i ListWorkerTodayOrdersRow
		if err := rows.Scan(
			&i.ID,
			&i.ObjectID,
			&i.DueDate,
			&i.Status,
			&i.VersionID,
			&i.ObjectName,
			&i.Address,
			&i.Lat,
			&i.Lon,
			&i.QrToken,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setWorkOrderStatus = `-- name: SetWorkOrderStatus :exec
UPDATE work_order SET status = $3 WHERE id = $1 AND tenant_id = $2
`

type SetWorkOrderStatusParams struct {
	ID       uuid.UUID
	TenantID uuid.UUID
	Status   WorkOrderStatus
}

func (q *Queries) SetWorkOrderStatus(ctx context.Context, arg SetWorkOrderStatusParams) error {
	_, err := q.db.Exec(ctx, setWorkOrderStatus, arg.ID, arg.TenantID, arg.Status)
	return err
}

const upsertWorkExecution = `-- name: UpsertWorkExecution :exec
INSERT INTO work_execution (
    id, tenant_id, work_order_id, worker_id, started_at, device_finished_at, finished_at, note
) VALUES (
    $1, $2, $3, $4,
    $5, $6,
    CASE WHEN $6::timestamptz IS NOT NULL THEN now() ELSE NULL END,
    $7
)
ON CONFLICT (id) DO UPDATE SET
    started_at         = EXCLUDED.started_at,
    -- Completion is evidence: once device_finished_at / finished_at are recorded
    -- they are permanent. A later in-progress snapshot (a delayed/out-of-order
    -- outbox retry) can never erase a recorded completion time. started_at / note
    -- still follow the latest snapshot.
    device_finished_at = COALESCE(work_execution.device_finished_at, EXCLUDED.device_finished_at),
    finished_at        = COALESCE(work_execution.finished_at,
                                  CASE WHEN EXCLUDED.device_finished_at IS NOT NULL THEN now() ELSE NULL END),
    note = EXCLUDED.note
WHERE work_execution.tenant_id = EXCLUDED.tenant_id
  AND work_execution.worker_id = EXCLUDED.worker_id
`

type UpsertWorkExecutionParams struct {
	ID               uuid.UUID
	TenantID         uuid.UUID
	WorkOrderID      uuid.UUID
	WorkerID         uuid.UUID
	StartedAt        pgtype.Timestamptz
	DeviceFinishedAt pgtype.Timestamptz
	Note             *string
}

// Full-state idempotent upsert. finished_at is server receipt time, stamped
// once when device_finished_at first becomes non-null (COALESCE keeps it stable
// across replays). The ON CONFLICT WHERE guard prevents a colliding id from a
// different tenant/worker overwriting an existing row (defense in depth).
func (q *Queries) UpsertWorkExecution(ctx context.Context, arg UpsertWorkExecutionParams) error {
	_, err := q.db.Exec(ctx, upsertWorkExecution,
		arg.ID,
		arg.TenantID,
		arg.WorkOrderID,
		arg.WorkerID,
		arg.StartedAt,
		arg.DeviceFinishedAt,
		arg.Note,
	)
	return err
}

const upsertWorkExecutionItem = `-- name: UpsertWorkExecutionItem :execrows
INSERT INTO work_execution_item (id, execution_id, template_item_id, checked, checked_at)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (id) DO UPDATE SET
    checked    = EXCLUDED.checked,
    checked_at = EXCLUDED.checked_at
WHERE work_execution_item.execution_id = EXCLUDED.execution_id
`

type UpsertWorkExecutionItemParams struct {
	ID             uuid.UUID
	ExecutionID    uuid.UUID
	TemplateItemID uuid.UUID
	Checked        bool
	CheckedAt      pgtype.Timestamptz
}

func (q *Queries) UpsertWorkExecutionItem(ctx context.Context, arg UpsertWorkExecutionItemParams) (int64, error) {
	result, err := q.db.Exec(ctx, upsertWorkExecutionItem,
		arg.ID,
		arg.ExecutionID,
		arg.TemplateItemID,
		arg.Checked,
		arg.CheckedAt,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
